FROM node:16.20.2

WORKDIR /app

COPY ./API_Management/package.json ./package.json
COPY ./API_Management/package-lock.json ./package-lock.json

RUN npm install

COPY ./API_Management ./

EXPOSE 3000

CMD ["node", "server.js"]
