version: '3'
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    # volumes:
    #   - ./Basic_Website:/usr/share/nginx/html

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    volumes:
      - ./API_Management:/app/API_Management
