name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Set up Docker Compose
      run: |
        sudo apt-get install -y docker-compose
        docker-compose --version
      
    - name: Start the Docker containers with docker-compose
      run: |
        docker-compose up -d
      working-directory: .

